# Lichess bot configuration for homemade UCI engine

token: "{lichess_api_token}"
url: "https://lichess.org/"

#engine:
  #dir: "C:/Users/DELL/Desktop/CHESS ENGINE/CodeSpaces/CHESS-Engine/src"
  #name: "myengine.exe"
engine:
  dir: "./engine"        # relative path to the folder containing the engine
  name: "myengine"       # name of the executable (no .exe on Linux)
  working_dir: ""
  protocol: "uci"
  ponder: true

  polyglot:
    enabled: false

  draw_or_resign:
    resign_enabled: false
    offer_draw_enabled: true

  online_moves:
    max_out_of_book_moves: 10
    max_retries: 2
    chessdb_book:
      enabled: false
    lichess_cloud_analysis:
      enabled: false
    lichess_opening_explorer:
      enabled: false
    online_egtb:
      enabled: false

  lichess_bot_tbs:
    syzygy:
      enabled: false
    gaviota:
      enabled: false

  uci_options: {}  # Empty because myengine.exe has no configurable UCI options

silence_stderr: false
abort_time: 30
fake_think_time: false
rate_limiting_delay: 0
move_overhead: 2000
max_takebacks_accepted: 0
quit_after_all_games_finish: false

correspondence:
  move_time: 60
  checkin_period: 300
  disconnect_time: 150
  ponder: false

challenge:
  concurrency: 1
  sort_by: "best"
  preference: "none"
  accept_bot: true
  only_bot: false
  max_increment: 20
  min_increment: 0
  max_base: 1800
  min_base: 0
  max_days: 14
  min_days: 1
  variants:
    - standard
  time_controls:
    - bullet
    - blitz
    - rapid
    - classical
  modes:
    - casual
  bullet_requires_increment: false
  max_simultaneous_games_per_user: 5

greeting:
  hello: "Hi! I'm {me}. Good luck! Type !help for a list of commands I can respond to."
  goodbye: "Good game!"
  hello_spectators: "Hi! I'm {me}. Type !help for a list of commands I can respond to."
  goodbye_spectators: "Thanks for watching!"

matchmaking:
  allow_matchmaking: false
  allow_during_games: false
  challenge_variant: "random"
  challenge_timeout: 30
  challenge_initial_time:
    - 60
    - 180
  challenge_increment:
    - 1
    - 2
  opponent_rating_difference: 300
  rating_preference: "none"
  challenge_mode: "random"
  challenge_filter: none
  include_challenge_block_list: false
